const { useState, useEffect, useRef } = React;

const SECTIONS = [
  { id: "challenges", label: "Challenges", icon: "⚡", color: "#E8B931" },
  { id: "time", label: "Time & Clocks", icon: "🕐", color: "#4A90D9" },
  { id: "consensus", label: "Consensus", icon: "🤝", color: "#50C878" },
  { id: "transactions", label: "Transactions", icon: "💰", color: "#E74C3C" },
  { id: "bigpicture", label: "Full Picture", icon: "🗺️", color: "#9B59B6" },
];

const S = [
  { id:0,section:"challenges",phase:"WHY",title:"Why Distributed Systems Are Hard",icon:"🌩️",color:"#E8B931",concepts:["Network Partition","Partial Failure","No Global Clock"],actors:["Data Center Mumbai","Network Link","Data Center Bangalore","Data Center Chennai"],
    simple:"Your food delivery app has grown. One server can't handle the load. You now have servers in Mumbai, Bangalore, and Chennai. Congratulations — you have a distributed system. And three nightmares that don't exist on a single machine:\n\n1. THE NETWORK IS UNRELIABLE. The link between Mumbai and Bangalore can drop at any moment.\n\n2. PARTIAL FAILURE. Mumbai works fine while Bangalore is down. Half your system works, half doesn't.\n\n3. NO GLOBAL CLOCK. Each server's clock is slightly different. When two events happen on different servers, which came first? You can't reliably tell.\n\nEvery concept in this chapter exists to deal with one of these three problems.",
    detail:"THE FALLACIES OF DISTRIBUTED COMPUTING (Peter Deutsch, 1994):\n\n8 assumptions that are FALSE:\n1. The network is reliable → FALSE (cables cut, routers crash)\n2. Latency is zero → FALSE (Mumbai to Bangalore = 5-20ms)\n3. Bandwidth is infinite → FALSE (links saturate)\n4. The network is secure → FALSE (eavesdropping, MITM)\n5. Topology doesn't change → FALSE (nodes added/removed)\n6. There is one administrator → FALSE (multiple teams)\n7. Transport cost is zero → FALSE (data transfer costs money)\n8. The network is homogeneous → FALSE (different hardware/OS)\n\nOn a SINGLE machine:\n  Function call: ~1 nanosecond, ALWAYS succeeds\n  Memory read: ~100 nanoseconds, ALWAYS succeeds\n\nIn a DISTRIBUTED system:\n  Network call: ~1-100 MILLISECONDS (1 million x slower!)\n  Might succeed, might fail, might succeed BUT RESPONSE IS LOST\n\nThe WORST scenario isn't failure. It's AMBIGUITY.\n\nYou send \"charge customer ₹500\" to Payment Service.\nNo response after 5 seconds. What happened?\n  A) Failed. Customer NOT charged. Safe to retry.\n  B) Succeeded but response lost. Customer IS charged. Retry = DOUBLE charge!\n  C) Still processing. Retry = possible duplicate!\n\nYou literally CANNOT KNOW. This is the fundamental challenge.\n\nWHY NOT JUST USE ONE MACHINE?\n  — Can't handle 100,000 req/sec\n  — 50ms latency for distant users\n  — One machine dying = entire system down\n  — Data sovereignty laws require regional storage",
    analogy:"🍕 A single restaurant: one kitchen, one manager, one clock. Now open 3 branches in 3 cities. Mumbai can't see Bangalore's kitchen. Phone might be dead. Clocks differ. Customer called both — one order or two? Every distributed system problem is a multi-branch coordination problem."
  },
  { id:1,section:"challenges",phase:"SPLIT BRAIN",title:"Network Partitions & Split Brain",icon:"🔌",color:"#E74C3C",concepts:["Network Partition","Split Brain","CAP Theorem"],actors:["Partition A (Mumbai)","BROKEN Link","Partition B (Bangalore)"],
    simple:"The network between Mumbai and Bangalore goes down. Both data centers work fine — they just can't talk. This is a NETWORK PARTITION.\n\nBoth sides have active users. Both must decide: keep serving (risk inconsistency) or stop (lose availability)? This is SPLIT BRAIN — two halves making independent, conflicting decisions.",
    detail:"SPLIT BRAIN — CONCRETE PROBLEM:\n\n\"Meghana Foods\" has 5 biryanis in stock. Replicated on both servers.\n\nNetwork partitions.\n\nMumbai side:\n  Rahul orders 1 → stock = 4\n  Priya orders 1 → stock = 3\n\nBangalore side (doesn't know about Mumbai):\n  Amit orders 1 → stock = 4\n  Sara orders 1 → stock = 3\n  Raj orders 1 → stock = 2\n\nNetwork heals. Mumbai says 3. Bangalore says 2.\nReal stock: 5 - 2 - 3 = 0! Both WRONG. 5 orders for 5 items = OVERSOLD.\n\nCAP THEOREM — during partition, choose:\n\nCP (Consistent + Partition Tolerant):\n  \"Go offline rather than give wrong answers.\"\n  One side STOPS writes. Others return errors.\n  Data NEVER inconsistent.\n  Used for: Payments, inventory, banking\n  Systems: ZooKeeper, etcd, HBase\n\nAP (Available + Partition Tolerant):\n  \"Give potentially stale answers rather than go offline.\"\n  Both sides keep serving. Merge conflicts later.\n  Used for: Social feeds, DNS, browsing\n  Systems: Cassandra, DynamoDB, CouchDB\n\nYOUR FOOD APP:\n  Payments → CP (money must be correct)\n  Restaurant browsing → AP (stale OK)\n  Inventory → CP (overselling is bad)\n\nDETECTING PARTITIONS:\nMumbai hasn't heard from Bangalore in 30s. Is it:\n  A) Dead? B) Alive but network down? C) Just slow?\nCan't tell the difference. Solution: HEARTBEATS.",
    analogy:"🍕 Two branches lose phone service. Both keep taking orders. Mumbai reserves last 2 tables. Bangalore also reserves last 2. Phone returns — 4 reservations, only 2 tables. CP: only Mumbai takes reservations during outage. AP: both keep taking, handle overbooking later."
  },
  { id:2,section:"challenges",phase:"HEARTBEATS",title:"Heartbeats & Handling Failures",icon:"💓",color:"#50C878",concepts:["Heartbeat","Failure Detection","Phi Accrual","Quorum"],actors:["Server A","Server B","Failure Detector"],
    simple:"If a server stops responding, you need to detect it. HEARTBEATS: every server sends periodic \"I'm alive\" messages. Miss N heartbeats → declared dead.\n\nThe dilemma: short timeout = fast detection but many false positives. Long timeout = few false alarms but slow detection of real failures.",
    detail:"HEARTBEAT MECHANISM:\n\nServer A → coordinator every 3 seconds:\n  t=0s: \"alive\" ✅  t=3s: \"alive\" ✅  t=6s: \"alive\" ✅\n  t=9s: silence  t=12s: silence  t=15s: silence → DEAD!\n\nBut what if A was alive and network was slow for 7 seconds?\n  t=16s: \"alive\" → FALSE POSITIVE! Removed healthy server for nothing.\n\nADAPTIVE DETECTION (Phi Accrual):\nLearn from history:\n  Normal intervals: [3.0s, 3.1s, 2.9s, 3.2s]\n  10s late → suspicious. 30s late → certainly dead.\n  Adapts to each network's normal behavior.\n  Used by: Cassandra, Akka.\n\nHANDLING FAILURES:\n1. FAILOVER: Backup takes over (replica → primary)\n2. RETRY with another node (must be idempotent!)\n3. CIRCUIT BREAKER: stop sending, periodically test\n4. QUORUM: 3/5 monitors agree \"dead\" before acting\n   Prevents one confused monitor from causing false failover.\n\nYOUR FOOD APP:\n  Redis Sentinel: 3 sentinels, 2/3 must agree master dead\n  Kubernetes: 3 missed heartbeats → pod restarted\n  Load balancer: ping/5s, 3 failures → remove from pool",
    analogy:"🍕 Each branch calls HQ every 5 min. No call 3 times → assumed closed, orders redirected. Problem: phone glitch = 100 orders diverted for nothing. Adaptive: HQ knows Mumbai calls at 5.0±0.2 min. 6 min gap = suspicious. 15 min = certainly closed."
  },
  { id:3,section:"time",phase:"CLOCK PROBLEM",title:"The Clock Synchronization Problem",icon:"🕐",color:"#4A90D9",concepts:["Clock Drift","NTP","Wall Clock","Monotonic Clock"],actors:["Server A (12:00:00.000)","Server B (12:00:00.047)","NTP Server"],
    simple:"Rahul places an order at \"12:00:00.000\" (Server A). Priya cancels it at \"11:59:59.990\" (Server B). Cancel came BEFORE the order? Impossible — Priya cancelled AFTER. But Server B's clock is 47ms behind.\n\nWhen different machines record events, you CANNOT trust their wall clocks for ordering. This is the clock synchronization problem.",
    detail:"WHY CLOCKS DRIFT:\nQuartz crystal: not perfect. Drift: 10-200 ppm → 0.8-17 seconds/day!\nAfter a week, servers differ by MINUTES.\n\nNTP: sync with atomic clocks. Accuracy: 10-50ms internet, 1ms local.\nGoogle TrueTime: GPS + atomic → ~7ms. But 1000 txns in 7ms!\n\nTWO TYPES OF CLOCKS:\n\nWALL CLOCK:\n  \"What time is it?\" → \"2024-01-15 12:00:00\"\n  — Can JUMP forward or BACKWARD (NTP correction!)\n  — BAD for ordering events\n  — Good for: displaying time to humans\n\nMONOTONIC CLOCK:\n  \"Nanoseconds since boot\" → always increases\n  — Never jumps. Different on every machine.\n  — GOOD for: timeouts, performance measurement\n\nWHY THIS MATTERS — distributed lock:\n  Wall clock: Lock at 12:00:00, expires 12:00:05.\n  NTP jumps to 12:00:10. Lock expired INSTANTLY!\n  Two servers hold the lock. BROKEN!\n\n  Monotonic: Lock at tick 1M, expires 1M+5000.\n  NTP doesn't affect monotonic. Correct!\n\nLESSON: Never use wall clocks for ordering across machines. Need LOGICAL clocks.",
    analogy:"🍕 Three branches, unsynchronized clocks. Cancel at 12:00:30 (Mumbai). Order at 12:00:45 (Chennai). Cancel BEFORE order? Clocks lying. Can't use wall clocks across branches."
  },
  { id:4,section:"time",phase:"LOGICAL CLOCKS",title:"Lamport Timestamps & Vector Clocks",icon:"🔢",color:"#9B59B6",concepts:["Lamport Timestamp","Vector Clock","Happens-Before","Causal Order"],actors:["Server A (counter)","Server B (counter)","Server C (counter)"],
    simple:"Physical clocks can't order events across machines. Leslie Lamport (1978) invented LOGICAL CLOCKS: forget real time, use COUNTERS.\n\nLamport timestamps answer: \"Did X happen before Y?\" Vector clocks go further: \"Were X and Y independent (concurrent)?\"",
    detail:"LAMPORT TIMESTAMPS:\n\nEvery server has counter=0. Two rules:\nRule 1: Before each event, increment counter.\nRule 2: Messages carry counter. Receiver: max(mine, received) + 1.\n\nEXAMPLE:\nA(Order)=0, B(Payment)=0, C(Restaurant)=0\n\n1. A: Receive order        → A=1\n2. A: Send \"charge\" to B   → A=2, msg=2\n3. B: Receive (2)          → B=max(0,2)+1=3\n4. B: Process payment      → B=4\n5. B: Send \"done\" to A     → B=5, msg=5\n6. A: Receive (5)          → A=max(2,5)+1=6\n7. A: Send to C            → A=7, msg=7\n8. C: Receive (7)          → C=max(0,7)+1=8\n\nOrder: 1<2<3<4<5<6<7<8 ✅\n\nLIMITATION: If Lamport(X)<Lamport(Y), X didn't necessarily CAUSE Y.\nC's local event at counter=2 vs A's event at counter=2: related? Can't tell!\n\n━━━ VECTOR CLOCKS ━━━\n\nEach server: vector of [A_count, B_count, C_count].\n\nRules: increment YOUR position. Messages carry full vector.\nReceiver: element-wise MAX, then +1 to own position.\n\nStart: A=[0,0,0] B=[0,0,0] C=[0,0,0]\n1. A: Order      → A=[1,0,0]\n2. A: Send to B  → A=[2,0,0], msg=[2,0,0]\n3. B: Receive    → max([0,0,0],[2,0,0])→[2,0,0]+1→ B=[2,1,0]\n4. B: Payment    → B=[2,2,0]\n5. C: Local      → C=[0,0,1]  ← independent!\n\nCOMPARING:\n[2,1,0] before [2,2,0]? 2≤2,1≤2,0≤0 → YES ✅\n[2,2,0] vs [0,0,1]? 2>0 but 0<1 → CONCURRENT! Independent events.\n\nLamport: cheap (1 int), total order, can't detect concurrency.\nVector: expensive (N ints), detects concurrent/conflicting writes.\n\nYOUR APP: event logging → Lamport. Multi-master replication → Vector clocks.",
    analogy:"🍕 Lamport = one counter per branch. Events increment it. Good for ordering, can't detect independence. Vector = each branch tracks counters for EVERY branch. Now you know: was one event caused by another, or did they happen independently?"
  },
  { id:5,section:"consensus",phase:"RAFT",title:"Consensus — Paxos, Raft & Leader Election",icon:"🗳️",color:"#50C878",concepts:["Consensus","Raft","Paxos","Leader Election","Gossip"],actors:["Node 1 (Leader)","Node 2 (Follower)","Node 3 (Follower)","Node 4","Node 5"],
    simple:"Five servers must agree: \"Who is leader?\" or \"Was this committed?\" If one disagrees → split brain.\n\nConsensus algorithms get unreliable servers to reliably agree, even when some crash or messages are lost. Raft and Paxos are the two most important.",
    detail:"WHY CONSENSUS IS HARD:\n\nBroadcast: A says \"inventory=7\". B never gets it. INCONSISTENT.\nWait for all: C crashes. No ACK. System STUCK.\n\nSolution: MAJORITY QUORUM. 5 servers, need 3.\nA gets ACK from C,D,E (3/5). COMMITTED! B catches up later.\nAny two majorities overlap → no conflicting decisions.\n\n━━━ RAFT ━━━\n\nRoles: Leader (handles writes), Followers (replicate), Candidate (wants to be leader).\n\nLEADER ELECTION:\n1. All start as followers. Random timeout: 150-300ms.\n2. First to timeout → Candidate. Votes for self. Asks others.\n3. Each votes for AT MOST ONE per term. Majority → Leader.\n4. Leader sends heartbeats to prevent new elections.\n\nRandom timeouts: one usually wins before others even start.\n\nLOG REPLICATION:\n1. Client: \"set inventory=7\"\n2. Leader: append to log [term=3, idx=42, \"set inventory=7\"]\n3. Send AppendEntries to followers\n4. Majority ACK → COMMITTED\n5. Everyone applies: inventory=7\n\nLeader crashes → timeout → new election → continues.\n\n━━━ PAXOS ━━━\nProposer/Acceptor/Learner. Prepare(n) → Promise → Accept(n,v) → Chosen.\nProvably correct but infamously hard. Most use Raft.\n\n━━━ GOSSIP PROTOCOL ━━━\nNot consensus — SPREADS information.\nA tells B,C. B tells D,E. Eventually everyone knows.\nScalable (few peers, not all). Fault-tolerant. Eventually consistent.\nUsed by: Cassandra, Consul, Redis Cluster.\n\nYOUR APP:\n  etcd (Raft): service discovery, leader election\n  Redis Sentinel (Raft-like): master failover\n  Cassandra (Gossip): cluster membership",
    analogy:"🍕 Consensus = 5 managers voting on prices (majority rules). Leader election = one is chair. Disconnects → vote new chair. Random timeout = each speaks at different time, one goes first. Gossip = one branch hears news, tells 2 others, they tell 2 more. All 50 know within minutes."
  },
  { id:6,section:"transactions",phase:"PROBLEM",title:"Why Distributed Transactions Are Hard",icon:"💥",color:"#E74C3C",concepts:["Distributed Transaction","Atomicity"],actors:["Order Service","Payment Service","Inventory Service","Notification Service"],
    simple:"Rahul's order needs: create order, charge payment, decrement stock, notify restaurant. Four services, four databases.\n\nOne database: one ACID transaction. Four databases? No single \"BEGIN TRANSACTION\" spans them all. If payment succeeds but inventory fails, Rahul is charged without a confirmed order.",
    detail:"SINGLE DATABASE (easy):\n  BEGIN;\n    INSERT orders; UPDATE inventory; INSERT payments;\n  COMMIT;\n  All or none. Simple.\n\nDISTRIBUTED (hard):\n  Order DB-A: INSERT orders\n  Payment DB-B: INSERT payments\n  Inventory DB-C: UPDATE inventory\n  Three machines. Three transaction logs.\n\nWHAT GOES WRONG:\n  — Order ✅, Payment ✅, Inventory → TIMEOUT\n    Is stock decremented? DON'T KNOW.\n  — Order ✅, Payment → FAILED\n    Order exists but shouldn't. Delete it?\n    What if Order Service crashes before deleting?\n  — All succeed but \"commit\" message lost to one service.\n    It rolls back. Others committed. INCONSISTENT.\n\nCore: no atomic commit across machines. Any communication can fail.\nProven impossible to solve perfectly (Two Generals Problem).\nBut we have practical solutions.",
    analogy:"🍕 4 chefs in different cities must finish their dish simultaneously. If one burns theirs, ALL must throw away and restart. But they communicate by phone — which might cut out."
  },
  { id:7,section:"transactions",phase:"2PC",title:"Two-Phase Commit (2PC)",icon:"2️⃣",color:"#F39C12",concepts:["2PC","Coordinator","Prepare","Commit","Blocking"],actors:["Coordinator","Payment DB","Inventory DB","Notification DB"],
    simple:"One server (Coordinator) orchestrates. Phase 1: \"CAN you commit?\" Phase 2: \"DO commit.\"\n\nLike a wedding: \"Do you take this transaction?\" \"I do.\" \"I now pronounce this committed.\"",
    detail:"PHASE 1: PREPARE\n  Coordinator → Payment: \"Prepare T1\"\n  Payment: checks, logs PREPARED → \"YES\" ✅\n  Coordinator → Inventory: \"Prepare T1\" → \"YES\" ✅\n  Coordinator → Notification: → \"YES\" ✅\n  All YES → Phase 2.\n\nPHASE 2: COMMIT\n  Coordinator logs \"COMMIT T1\"\n  → Payment: \"COMMIT\" → Inventory: \"COMMIT\" → Notification: \"COMMIT\"\n  Each commits + ACKs. Done!\n\nIF ANY SAYS NO: → All: \"ABORT\". Everyone rolls back.\n\nTHE BLOCKING PROBLEM:\n  All voted YES. Coordinator CRASHES before Phase 2.\n  Participants:\n  — Promised to commit (resources locked)\n  — Don't know: COMMIT or ABORT?\n  — Can't commit (coordinator might've aborted)\n  — Can't abort (coordinator might've committed)\n  — STUCK. Locked. Potentially FOREVER.\n\nPERFORMANCE:\n  — Synchronous (waits for ALL each phase)\n  — One slow participant slows EVERYONE\n  — Resources locked during both phases\n  — 4+ messages per participant\n\n2PC: CORRECT but SLOW and FRAGILE.\nUsed by: XA transactions (legacy).\nAvoided by: modern microservices.",
    analogy:"🍕 Wedding. Phase 1: \"Do you?\" Both: \"I do.\" Phase 2: \"Committed!\" Officiant has heart attack between phases: both said \"I do\" but nobody said \"committed.\" Stuck at the altar — can't leave, can't proceed. That's the blocking problem."
  },
  { id:8,section:"transactions",phase:"SAGA",title:"Three-Phase Commit & SAGA Pattern",icon:"🔄",color:"#9B59B6",concepts:["3PC","SAGA","Compensating Transaction","Choreography","Orchestration"],actors:["Saga Orchestrator","Order Service","Payment Service","Inventory Service"],
    simple:"2PC blocks. 3PC adds a phase to fix it. But the real winner is the SAGA pattern: break the transaction into steps, use COMPENSATING ACTIONS to undo if a later step fails. Not atomic — eventually consistent — but practical.",
    detail:"━━━ 3PC ━━━\nAdds PRE-COMMIT:\n  Phase 1: Vote. Phase 2: \"Everyone agreed, get ready.\"\n  Phase 3: \"Commit.\"\nIf coordinator crashes after Phase 2: participants KNOW everyone agreed → proceed alone.\nBut: more messages, doesn't handle partitions well. Rarely used.\n\n━━━ SAGA PATTERN ━━━\n\nSequence of local transactions, each with a compensating action.\n\nRahul's Order:\n  Step 1: Create order (PENDING)\n  Step 2: Charge ₹640\n  Step 3: Decrement stock\n  Step 4: Notify restaurant\n\nHappy: all succeed → confirmed!\n\nStep 3 FAILS (out of stock):\n  Compensate Step 2: REFUND ₹640\n  Compensate Step 1: status → CANCELLED\n  Each compensation is a NEW transaction.\n\nCHOREOGRAPHY (event-driven):\n  1. Order created → publishes \"OrderCreated\"\n  2. Payment hears → charges → publishes \"PaymentCharged\"\n  3. Inventory hears → FAILS → publishes \"StockFailed\"\n  4. Payment hears → refunds → \"PaymentRefunded\"\n  5. Order hears → cancels\n  ✅ No single point of failure ❌ Hard to track/debug\n\nORCHESTRATION (central coordinator):\n  Orchestrator:\n  1. \"Create order\" → ok\n  2. \"Charge ₹640\" → ok\n  3. \"Reserve stock\" → FAIL!\n  4. \"Refund ₹640\" (compensate)\n  5. \"Cancel order\" (compensate)\n  ✅ Clear, debuggable ❌ Coordinator = SPOF\n\nSAGA vs 2PC:\n  2PC: true atomic, blocking, slow\n  SAGA: eventually consistent, no locks, fast, compensation-based\n\nDIRTY SECRET: Between steps, state is inconsistent.\nAfter payment but before stock: charged without confirmed order.\nMitigation: status PENDING→CHARGED→CONFIRMED, show \"Processing...\"",
    analogy:"🍕 2PC = plate all courses simultaneously; one fails = throw all away. SAGA = serve one at a time; course 3 fails = refund appetizer, bring back bread. Choreography = kitchens listen for bells. Orchestration = head chef directs step by step."
  },
  { id:9,section:"transactions",phase:"OUTBOX",title:"Outbox Pattern — Reliable Event Publishing",icon:"📮",color:"#1ABC9C",concepts:["Outbox Pattern","Dual Write","CDC"],actors:["Order Service","Order DB","Outbox Table","CDC/Debezium","Kafka"],
    simple:"Dual write problem: save to DB AND publish to Kafka. DB succeeds + Kafka fails = order with no event. Kafka succeeds + DB fails = event for nothing.\n\nOutbox Pattern: write the event to an \"outbox\" table in the SAME database, in the SAME transaction. Separate process reads outbox → publishes to Kafka. One transaction = both succeed or both fail.",
    detail:"THE DUAL WRITE PROBLEM:\n  await db.insert(\"orders\", order);         // DB\n  await kafka.publish(\"order.placed\", order); // Kafka\n  DB ok + Kafka fail → order exists, nobody notified.\n  Kafka ok + DB fail → event for non-existent order!\n\nOUTBOX SOLUTION:\n\nStep 1: ONE transaction:\n  BEGIN;\n    INSERT INTO orders (id, total) VALUES ('456', 640);\n    INSERT INTO outbox (event_type, payload)\n      VALUES ('order.placed', '{\"order_id\":\"456\"}');\n  COMMIT;\n  Both or neither. No dual write!\n\nStep 2: Publish from outbox:\n\n  POLLING: Every 100ms:\n    SELECT FROM outbox WHERE published=false;\n    For each: kafka.publish(); SET published=true;\n\n  CDC (Debezium): watches outbox table.\n    Every INSERT → auto-publishes to Kafka. No polling.\n\nCRASH SAFETY:\n  Polling: next poll picks up unpublished. Self-healing!\n  CDC: resumes from saved position. No events lost.\n\nDUPLICATES:\n  Publisher crashes after publish, before marking done.\n  Next run: publishes again. DUPLICATE!\n  Solution: IDEMPOTENT consumers. Check event ID.\n\nOUTBOX TABLE:\n  CREATE TABLE outbox (\n    id UUID PRIMARY KEY,\n    event_type VARCHAR(100),\n    payload JSONB,\n    created_at TIMESTAMP DEFAULT NOW(),\n    published BOOLEAN DEFAULT false\n  );\n\nOutbox + CDC + idempotent consumers = reliable event-driven architecture.\nUsed by: Netflix, Uber, Airbnb.",
    analogy:"🍕 Waiter writes TWO things simultaneously: order in kitchen log AND ticket on outbox rail. Runner carries tickets to stations. Drops one? Next runner picks it up. Delivered twice? Kitchen checks ticket number: \"Already made #456, skip.\" Writing both = ONE atomic action."
  },
  { id:10,section:"bigpicture",phase:"FULL PICTURE",title:"Everything Connected — Your Distributed Food App",icon:"🗺️",color:"#9B59B6",concepts:["Consensus","SAGA","Outbox","Clocks","Heartbeats","Gossip"],actors:["Rahul","Mumbai DC","Bangalore DC","Kafka","etcd","Services"],
    simple:"Let's trace Rahul's order through the distributed systems lens. Every concept in its natural place.",
    detail:"RAHUL ORDERS BIRYANI — DISTRIBUTED VIEW:\n\n━━━ INFRASTRUCTURE (always running) ━━━\n\nETCD (3 nodes, Raft):\n  Leader elected. Stores service registry, config, locks.\n  Leader dies → election ~300ms → new leader.\n\nHEARTBEATS:\n  Every service → health checker every 5s.\n  3 missed → unhealthy → restart on healthy node.\n\nGOSSIP:\n  Nodes tell random peers about cluster state.\n  All nodes learn changes within seconds.\n\n━━━ ORDER FLOW ━━━\n\n1. REQUEST: Rahul → Mumbai DC (DNS geo-routing).\n\n2. ORDER (Outbox Pattern):\n   BEGIN; INSERT order + INSERT outbox; COMMIT;\n   Lamport timestamp: T=42\n\n3. CDC → KAFKA: Debezium → \"order.placed\"\n\n4. SAGA (Orchestrator):\n   Step 1 → Payment: charge ₹640\n     BEGIN; INSERT payment + outbox; COMMIT; T=45\n   Step 2 → Inventory: lock via etcd (Raft)\n     Decrement stock. BEGIN; UPDATE + outbox; COMMIT; T=48\n   Step 3 → Notification: Kafka → restaurant tablet\n\n5. COMPLETE: status → CONFIRMED\n\n━━━ FAILURE: Out of stock ━━━\n   Step 2 fails → compensate:\n   → Refund ₹640 (compensating transaction)\n   → Cancel order\n   → Rahul: \"Sorry, sold out. Refunded.\"\n\n━━━ NETWORK PARTITION ━━━\n   Mumbai ←✗→ Bangalore\n\n   Mumbai (etcd majority): continues normally.\n   Bangalore (no majority): etcd read-only.\n     Payments → rejected (CP)\n     Browsing → works from replicas (AP)\n\n   Heals: etcd catches up. Gossip spreads. Kafka drains.\n\n━━━ CONCEPT MAP ━━━\n\nPROBLEM                  → SOLUTION\nCan't trust clocks       → Lamport Timestamps\nDetect concurrent edits  → Vector Clocks\nDetect failures          → Heartbeats (Phi Accrual)\nAgree on leader/config   → Raft (etcd)\nSpread cluster info      → Gossip Protocol\nTransactions across DBs  → SAGA (not 2PC)\nReliable event publish   → Outbox + CDC\nNetwork partition        → CP for money, AP for browsing\nDuplicate events         → Idempotent consumers\n\nEvery concept solves ONE failure mode.\nTogether: unreliable machines → reliable system.",
    analogy:"🍕 Your food empire across India:\n\nRaft = board voting (majority rules)\nHeartbeats = branches calling HQ\nGossip = managers sharing news\nLamport = event counter on receipts\nVector clocks = tracking what every branch did\nSAGA = step-by-step: kitchen fails → refund\nOutbox = order + ticket written together\n2PC = all branches plate simultaneously (fragile)\nPartition = phone lines cut between cities\nSplit brain = both think they're the main branch\nCompensation = \"main course failed, refunding appetizer\"\n\nEvery concept solves ONE failure. Together: reliable system."
  }
];

function Tag({label}){return <span style={{display:"inline-block",padding:"3px 10px",borderRadius:"100px",fontSize:"10.5px",fontWeight:700,letterSpacing:".5px",background:"rgba(255,255,255,.07)",color:"rgba(255,255,255,.65)",border:"1px solid rgba(255,255,255,.1)",marginRight:5,marginBottom:4,textTransform:"uppercase"}}>{label}</span>}

function Chain({actors,color}){return <div style={{display:"flex",alignItems:"center",flexWrap:"wrap",gap:4,marginTop:10,marginBottom:6}}>{actors.map((a,i)=><span key={i} style={{display:"flex",alignItems:"center",gap:4}}><span style={{padding:"3px 9px",borderRadius:6,fontSize:"10.5px",fontWeight:600,background:i===0?color+"20":"rgba(255,255,255,.04)",color:i===0?color:"rgba(255,255,255,.55)",border:`1px solid ${i===0?color+"40":"rgba(255,255,255,.07)"}`,whiteSpace:"nowrap"}}>{a}</span>{i<actors.length-1&&<span style={{color:"rgba(255,255,255,.2)",fontSize:11}}>→</span>}</span>)}</div>}

function App(){
  const[activeStep,setActiveStep]=useState(0);
  const[showDetail,setShowDetail]=useState(false);
  const[showAnalogy,setShowAnalogy]=useState(false);
  const[activeSection,setActiveSection]=useState("challenges");
  const contentRef=useRef(null);
  const step=S[activeStep];
  const sectionSteps=S.filter(s=>s.section===activeSection);
  const curSec=SECTIONS.find(s=>s.id===activeSection);
  const gi=S.indexOf(step);
  const canP=gi>0,canN=gi<S.length-1;

  useEffect(()=>{setShowDetail(false);setShowAnalogy(false);if(contentRef.current)contentRef.current.scrollTop=0},[activeStep]);
  useEffect(()=>{const f=S.findIndex(s=>s.section===activeSection);if(f>=0)setActiveStep(f)},[activeSection]);

  const nav=(d)=>{const n=gi+d;if(n>=0&&n<S.length){setActiveSection(S[n].section);setActiveStep(S[n].id)}};

  return(
    <div style={{minHeight:"100vh",background:"#0A0D12",color:"#E6EDF3",fontFamily:"'IBM Plex Sans',-apple-system,sans-serif",display:"flex",flexDirection:"column"}}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@400;500;600&display=swap');*{box-sizing:border-box;margin:0;padding:0}::-webkit-scrollbar{width:4px}::-webkit-scrollbar-track{background:transparent}::-webkit-scrollbar-thumb{background:rgba(255,255,255,.12);border-radius:10px}`}</style>

      <div style={{padding:"14px 18px 10px",borderBottom:"1px solid rgba(255,255,255,.05)"}}>
        <div style={{fontSize:10,fontWeight:700,textTransform:"uppercase",letterSpacing:2,color:"rgba(255,255,255,.25)",marginBottom:3,fontFamily:"'IBM Plex Mono',monospace"}}>System Design — Part 7</div>
        <div style={{fontSize:17,fontWeight:800,color:"#fff",lineHeight:1.3}}>Distributed Systems: When Things Break</div>
        <div style={{fontSize:11.5,color:"rgba(255,255,255,.35)",marginTop:3}}>Partitions, clocks, consensus & transactions across data centers</div>
      </div>

      <div style={{padding:"8px 18px",borderBottom:"1px solid rgba(255,255,255,.05)",overflowX:"auto"}}>
        <div style={{display:"flex",gap:3,minWidth:"fit-content"}}>
          {SECTIONS.map(sec=><button key={sec.id} onClick={()=>setActiveSection(sec.id)} style={{display:"flex",alignItems:"center",gap:4,padding:"6px 10px",borderRadius:7,border:activeSection===sec.id?`1.5px solid ${sec.color}50`:"1.5px solid transparent",background:activeSection===sec.id?sec.color+"14":"rgba(255,255,255,.025)",color:activeSection===sec.id?sec.color:"rgba(255,255,255,.35)",cursor:"pointer",fontSize:10.5,fontWeight:activeSection===sec.id?700:500,fontFamily:"'IBM Plex Sans',sans-serif",whiteSpace:"nowrap"}}><span style={{fontSize:11}}>{sec.icon}</span><span>{sec.label}</span></button>)}
        </div>
      </div>

      <div style={{padding:"7px 18px",borderBottom:"1px solid rgba(255,255,255,.04)",overflowX:"auto"}}>
        <div style={{display:"flex",gap:3,minWidth:"fit-content"}}>
          {sectionSteps.map(s=><button key={s.id} onClick={()=>setActiveStep(s.id)} style={{padding:"5px 9px",borderRadius:6,border:activeStep===s.id?`1px solid ${s.color}40`:"1px solid transparent",background:activeStep===s.id?s.color+"10":"transparent",color:activeStep===s.id?s.color:"rgba(255,255,255,.3)",cursor:"pointer",fontSize:10.5,fontWeight:activeStep===s.id?700:500,fontFamily:"'IBM Plex Sans',sans-serif",whiteSpace:"nowrap"}}>{s.icon} {s.phase}</button>)}
        </div>
      </div>

      <div style={{height:2,background:"rgba(255,255,255,.03)"}}><div style={{height:"100%",width:`${((gi+1)/S.length)*100}%`,background:`linear-gradient(90deg,${step.color}88,${step.color})`,transition:"all .4s ease"}}/></div>

      <div ref={contentRef} style={{flex:1,overflow:"auto",padding:"14px 18px 110px"}}>
        <div style={{marginBottom:12}}>
          <div style={{display:"flex",alignItems:"center",gap:7,marginBottom:7}}>
            <span style={{fontSize:9,fontWeight:800,color:curSec.color,background:curSec.color+"18",padding:"2px 7px",borderRadius:4,fontFamily:"'IBM Plex Mono',monospace",letterSpacing:1}}>{curSec.label.toUpperCase()}</span>
            <span style={{fontSize:9,fontWeight:700,color:"rgba(255,255,255,.25)",fontFamily:"'IBM Plex Mono',monospace"}}>{gi+1} / {S.length}</span>
          </div>
          <h2 style={{fontSize:19,fontWeight:800,color:"#fff",lineHeight:1.3,marginBottom:7}}>{step.icon} {step.title}</h2>
          <div style={{display:"flex",flexWrap:"wrap",gap:2}}>{step.concepts.map((c,i)=><Tag key={i} label={c}/>)}</div>
        </div>
        <div style={{fontSize:9.5,fontWeight:700,textTransform:"uppercase",letterSpacing:1,color:"rgba(255,255,255,.22)",marginBottom:1}}>Who's involved</div>
        <Chain actors={step.actors} color={step.color}/>
        <div style={{background:"rgba(255,255,255,.025)",borderRadius:11,padding:15,border:"1px solid rgba(255,255,255,.055)",marginTop:12,fontSize:13.5,lineHeight:1.75,color:"rgba(255,255,255,.78)",whiteSpace:"pre-wrap"}}>{step.simple}</div>

        <button onClick={()=>setShowDetail(!showDetail)} style={{display:"flex",alignItems:"center",gap:7,width:"100%",padding:"11px 15px",marginTop:7,borderRadius:10,border:`1px solid ${step.color}30`,background:showDetail?step.color+"10":"transparent",color:step.color,cursor:"pointer",fontSize:12.5,fontWeight:700,fontFamily:"'IBM Plex Sans',sans-serif"}}>
          <span style={{transform:showDetail?"rotate(90deg)":"rotate(0deg)",transition:"transform .2s",fontSize:13}}>▶</span>{showDetail?"Hide":"Show"} Technical Deep Dive
        </button>
        {showDetail&&<div style={{background:"rgba(0,0,0,.3)",borderRadius:10,padding:16,border:`1px solid ${step.color}20`,marginTop:3,fontSize:12,lineHeight:1.85,color:"rgba(255,255,255,.7)",fontFamily:"'IBM Plex Mono',monospace",whiteSpace:"pre-wrap"}}>{step.detail}</div>}

        <button onClick={()=>setShowAnalogy(!showAnalogy)} style={{display:"flex",alignItems:"center",gap:7,width:"100%",padding:"11px 15px",marginTop:5,borderRadius:10,border:"1px solid rgba(255,255,255,.08)",background:showAnalogy?"rgba(255,255,255,.04)":"transparent",color:"rgba(255,255,255,.6)",cursor:"pointer",fontSize:12.5,fontWeight:700,fontFamily:"'IBM Plex Sans',sans-serif"}}>
          <span style={{transform:showAnalogy?"rotate(90deg)":"rotate(0deg)",transition:"transform .2s",fontSize:13}}>▶</span>{showAnalogy?"Hide":"Show"} Real-World Analogy
        </button>
        {showAnalogy&&<div style={{background:"rgba(255,255,255,.025)",borderRadius:10,padding:15,border:"1px solid rgba(255,255,255,.07)",marginTop:3,fontSize:13.5,lineHeight:1.75,color:"rgba(255,255,255,.6)"}}>{step.analogy}</div>}
      </div>

      <div style={{position:"fixed",bottom:0,left:0,right:0,padding:"10px 18px 16px",background:"linear-gradient(transparent,#0A0D12 30%)",display:"flex",gap:8}}>
        <button onClick={()=>nav(-1)} disabled={!canP} style={{flex:1,padding:12,borderRadius:10,border:"1px solid rgba(255,255,255,.08)",background:"rgba(255,255,255,.04)",color:canP?"rgba(255,255,255,.65)":"rgba(255,255,255,.18)",cursor:canP?"pointer":"default",fontSize:13,fontWeight:700,fontFamily:"'IBM Plex Sans',sans-serif"}}>← Back</button>
        <button onClick={()=>nav(1)} disabled={!canN} style={{flex:2,padding:12,borderRadius:10,border:"none",background:canN?`linear-gradient(135deg,${step.color},${step.color}99)`:"rgba(255,255,255,.08)",color:canN?"#fff":"rgba(255,255,255,.25)",cursor:canN?"pointer":"default",fontSize:13,fontWeight:700,fontFamily:"'IBM Plex Sans',sans-serif"}}>{canN?"Next →":"Distributed systems mastered!"}</button>
      </div>
    </div>
  );
}
